"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Plus, Sparkles, Trash2 } from "lucide-react";
import { createAsset, deleteAsset, listAssets, listProjects, type InfrastructureAsset, type Project } from "../lib/api";
import "../app/globals.css";

type AssetInventoryProps = { category: InfrastructureAsset["category"]; eyebrow: string; title: string; description: string };

export default function AssetInventory({ category, eyebrow, title, description }: AssetInventoryProps) {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [assets, setAssets] = useState<InfrastructureAsset[]>([]); const [name, setName] = useState(""); const [status, setStatus] = useState<InfrastructureAsset["status"]>("planned"); const [location, setLocation] = useState(""); const [details, setDetails] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const token = window.localStorage.getItem("aether_access_token"); if (token) listProjects(token).then((loaded) => { setProjects(loaded); setProjectId(loaded[0]?.id ?? ""); }); }, []);
  useEffect(() => { const token = window.localStorage.getItem("aether_access_token"); if (token && projectId) listAssets(token, projectId, category).then(setAssets).catch(() => setAssets([])); }, [category, projectId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const token = window.localStorage.getItem("aether_access_token"); if (!token || !projectId || !name.trim()) return; try { const asset = await createAsset(token, projectId, { category, name: name.trim(), status, location: location.trim(), details: details.trim() }); setAssets((current) => [...current, asset]); setName(""); setLocation(""); setDetails(""); setMessage("Asset recorded"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record asset"); } }
  async function remove(assetId: string) { const token = window.localStorage.getItem("aether_access_token"); if (!token || !projectId) return; try { await deleteAsset(token, projectId, assetId); setAssets((current) => current.filter((asset) => asset.id !== assetId)); setMessage("Asset removed"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to remove asset"); } }
  return <main className="imports-shell"><header className="floorplan-header"><a href="/"><ArrowLeft size={16} /> Console</a><div className="auth-brand"><div className="brand-mark"><Sparkles size={18} /></div><div><strong>AETHER-IT</strong><span>{title}</span></div></div><span className="floorplan-status"><span className="pulse" /> VPS CONNECTED</span></header><section className="imports-workspace"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p><section className="import-card panel"><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Select a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><form className="asset-form" onSubmit={submit}><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Asset name" /><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="planned">Planned</option><option value="active">Active</option><option value="warning">Warning</option><option value="retired">Retired</option></select><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Location" /><input value={details} onChange={(event) => setDetails(event.target.value)} placeholder="Details" /><button disabled={!projectId}><Plus size={14} /> Add asset</button></form>{message && <p className="upload-status success">{message}</p>}<div className="device-inventory">{assets.map((asset) => <div className="inventory-row" key={asset.id}><div><b>{asset.name}</b><small>{asset.status.toUpperCase()} · {asset.location || "Unlocated"}{asset.details ? ` · ${asset.details}` : ""}</small></div><button className="icon-action" title="Delete asset" onClick={() => remove(asset.id)}><Trash2 size={14} /></button></div>)}{!assets.length && <div className="empty-allocations">No dedicated assets recorded yet.</div>}</div></section></section><footer className="statusbar"><span><Sparkles size={12} /> AI ENGINE: Gemini 3 Flash</span><span>{category.toUpperCase()} ASSETS</span><span>VPS CONNECTED</span></footer></main>;
}
