"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, FileCheck2, Sparkles } from "lucide-react";
import { getTopology, listProjects, listTasks, type Project, type ProjectTask, type Topology } from "../../lib/api";
import "../globals.css";

export default function CompliancePage() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [topology, setTopology] = useState<Topology>({ nodes: [], links: [] }); const [tasks, setTasks] = useState<ProjectTask[]>([]);
  useEffect(() => { const token = window.localStorage.getItem("aether_access_token"); if (token) listProjects(token).then((loaded) => { setProjects(loaded); setProjectId(loaded[0]?.id ?? ""); }); }, []);
  useEffect(() => { const token = window.localStorage.getItem("aether_access_token"); if (token && projectId) { getTopology(token, projectId).then(setTopology).catch(() => setTopology({ nodes: [], links: [] })); listTasks(token, projectId).then(setTasks).catch(() => setTasks([])); } }, [projectId]);
  const checks = [{ label: "Topology documented", passed: topology.nodes.length > 0 }, { label: "Links documented", passed: topology.links.length > 0 }, { label: "Open tasks reviewed", passed: tasks.filter((task) => task.status !== "done").length === 0 }, { label: "Project export available", passed: true }]; const score = Math.round((checks.filter((check) => check.passed).length / checks.length) * 100);
  return <main className="imports-shell"><header className="floorplan-header"><a href="/"><ArrowLeft size={16} /> Console</a><div className="auth-brand"><div className="brand-mark"><Sparkles size={18} /></div><div><strong>AETHER-IT</strong><span>Compliance review</span></div></div><span className="floorplan-status"><span className="pulse" /> VPS CONNECTED</span></header><section className="imports-workspace"><span className="eyebrow">CONTROL / COMPLIANCE</span><h1>Turn evidence into a reviewable score.</h1><p>Project checks are grounded in the current topology and task queue.</p><section className="import-card panel"><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Select a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="compliance-score"><strong>{score}%</strong><span>project readiness score</span></div><div className="device-inventory">{checks.map((check) => <div className="inventory-row" key={check.label}><span className="member-avatar">{check.passed ? <CheckCircle2 size={15} /> : <FileCheck2 size={15} />}</span><div><b>{check.label}</b><small>{check.passed ? "PASS" : "REVIEW REQUIRED"}</small></div><span className={check.passed ? "online-dot" : "task-priority priority-high"} /></div>)}</div></section></section><footer className="statusbar"><span><Sparkles size={12} /> AI ENGINE: Gemini 3 Flash</span><span>COMPLIANCE REVIEW</span><span>VPS CONNECTED</span></footer></main>;
}
